/* SQLParserTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. SQLParserTokenManager.java */
package com.granveaud.mysql2h2converter.parser;
import java.util.*;
import java.io.*;
import com.granveaud.mysql2h2converter.sql.*;

/** Token Manager. */
public class SQLParserTokenManager implements SQLParserConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x4200404000000L) != 0L)
         {
            jjmatchedKind = 103;
            return 29;
         }
         if ((active0 & 0xfffbdffbfbffff80L) != 0L || (active1 & 0x7fffffffffL) != 0L)
         {
            jjmatchedKind = 103;
            return 48;
         }
         return -1;
      case 1:
         if ((active0 & 0xffffbffffeff9f80L) != 0L || (active1 & 0x7f7ffff77fL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 103;
               jjmatchedPos = 1;
            }
            return 48;
         }
         if ((active0 & 0x400001006000L) != 0L || (active1 & 0x80000880L) != 0L)
            return 48;
         return -1;
      case 2:
         if ((active0 & 0xfbffbffcfabf9d80L) != 0L || (active1 & 0x7f6fff777fL) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 103;
               jjmatchedPos = 2;
            }
            return 48;
         }
         if ((active0 & 0x400400305404200L) != 0L || (active1 & 0x10008000L) != 0L)
            return 48;
         return -1;
      case 3:
         if ((active0 & 0x79bbe0f6f8bb9480L) != 0L || (active1 & 0x7e4dff775fL) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 103;
               jjmatchedPos = 3;
            }
            return 48;
         }
         if ((active0 & 0x82441f0802040900L) != 0L || (active1 & 0x122008020L) != 0L)
            return 48;
         return -1;
      case 4:
         if ((active0 & 0xc9bbaab6f8b99480L) != 0L || (active1 & 0x6807de774bL) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 103;
               jjmatchedPos = 4;
            }
            return 48;
         }
         if ((active0 & 0x3000404000020000L) != 0L || (active1 & 0x1648210014L) != 0L)
            return 48;
         return -1;
      case 5:
         if ((active0 & 0x89bb8aa2f8b91080L) != 0L || (active1 & 0x20078e064bL) != 0L)
         {
            jjmatchedKind = 103;
            jjmatchedPos = 5;
            return 48;
         }
         if ((active0 & 0x4000201400008400L) != 0L || (active1 & 0x4840517100L) != 0L)
            return 48;
         return -1;
      case 6:
         if ((active0 & 0x89ba0a00f0111080L) != 0L || (active1 & 0x2003860208L) != 0L)
         {
            jjmatchedKind = 103;
            jjmatchedPos = 6;
            return 48;
         }
         if ((active0 & 0x180a208a80000L) != 0L || (active1 & 0x4080443L) != 0L)
            return 48;
         return -1;
      case 7:
         if ((active0 & 0x888080080110080L) != 0L || (active1 & 0x2003860008L) != 0L)
         {
            jjmatchedKind = 103;
            jjmatchedPos = 7;
            return 48;
         }
         if ((active0 & 0x8132020070001000L) != 0L || (active1 & 0x200L) != 0L)
            return 48;
         return -1;
      case 8:
         if ((active0 & 0x888000000100000L) != 0L || (active1 & 0x2001060008L) != 0L)
         {
            jjmatchedKind = 103;
            jjmatchedPos = 8;
            return 48;
         }
         if ((active0 & 0x80080010080L) != 0L || (active1 & 0x2800000L) != 0L)
            return 48;
         return -1;
      case 9:
         if ((active0 & 0x888000000000000L) != 0L || (active1 & 0x8L) != 0L)
            return 48;
         if ((active0 & 0x100000L) != 0L || (active1 & 0x2001060000L) != 0L)
         {
            jjmatchedKind = 103;
            jjmatchedPos = 9;
            return 48;
         }
         return -1;
      case 10:
         if ((active0 & 0x100000L) != 0L || (active1 & 0x1060000L) != 0L)
         {
            jjmatchedKind = 103;
            jjmatchedPos = 10;
            return 48;
         }
         if ((active1 & 0x2000000000L) != 0L)
            return 48;
         return -1;
      case 11:
         if ((active0 & 0x100000L) != 0L || (active1 & 0x1040000L) != 0L)
         {
            jjmatchedKind = 103;
            jjmatchedPos = 11;
            return 48;
         }
         if ((active1 & 0x20000L) != 0L)
            return 48;
         return -1;
      case 12:
         if ((active0 & 0x100000L) != 0L || (active1 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 103;
            jjmatchedPos = 12;
            return 48;
         }
         if ((active1 & 0x40000L) != 0L)
            return 48;
         return -1;
      case 13:
         if ((active1 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 103;
            jjmatchedPos = 13;
            return 48;
         }
         if ((active0 & 0x100000L) != 0L)
            return 48;
         return -1;
      case 14:
         if ((active1 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 103;
            jjmatchedPos = 14;
            return 48;
         }
         return -1;
      case 15:
         if ((active1 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 103;
            jjmatchedPos = 15;
            return 48;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 34:
         return jjStopAtPos(0, 116);
      case 39:
         return jjStopAtPos(0, 115);
      case 40:
         return jjStopAtPos(0, 118);
      case 41:
         return jjStopAtPos(0, 119);
      case 44:
         return jjStopAtPos(0, 121);
      case 59:
         return jjStopAtPos(0, 117);
      case 61:
         return jjStopAtPos(0, 120);
      case 63:
         return jjStopAtPos(0, 122);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x400001100000L, 0x98001000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x4200404000000L, 0x0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x800100000800400L, 0x4007000404L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x33002081880L, 0x880100L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x200000000008000L, 0x0L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x8000004000000000L, 0x22L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x40000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x2000000300002000L, 0x10c000L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa1_0(0x400000L, 0x0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x110000000000000L, 0x220020000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x88000080000000L, 0x10L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x8000044000L, 0x800L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x200000L, 0x40L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x800000000L, 0x100000208L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x400000040000000L, 0x1000400001L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x620c0008030100L, 0x2040000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa1_0(0x5000800010000200L, 0x800002000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa1_0(0x1000000000000L, 0x210000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400000000L);
      case 90:
      case 122:
         return jjMoveStringLiteralDfa1_0(0x20000000L, 0x0L);
      default :
         return jjMoveNfa_0(2, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x1030000021000L, active1, 0x40210450L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x1000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x10000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x4c80028a2490080L, active1, 0x100480308L);
      case 70:
      case 102:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(1, 13, 48);
         break;
      case 71:
      case 103:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x100000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000000L, active1, 0x2000004L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x222c040c000000L, active1, 0x40000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x4004000000000L, active1, 0x8000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L, active1, 0L);
      case 78:
      case 110:
         if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(1, 71, 48);
         return jjMoveStringLiteralDfa2_0(active0, 0x6200800310000000L, active1, 0x80000c000L);
      case 79:
      case 111:
         if ((active1 & 0x800L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x910001000804100L, active1, 0x4224020002L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x2001L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x200c00L, active1, 0x2400000000L);
      case 83:
      case 115:
         if ((active1 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 95;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x1000400001000200L, active1, 0L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x1000000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000008000140000L, active1, 0x1800020L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x100840000000L, active1, 0x3102000001L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000L, active1, 0x40000000L);
      case 67:
      case 99:
         if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x402000000000L, active1, 0x220000000L);
      case 68:
      case 100:
         if ((active1 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(2, 92, 48);
         return jjMoveStringLiteralDfa3_0(active0, 0x2088000080000100L, active1, 0x2000L);
      case 69:
      case 101:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 9, 48);
         return jjMoveStringLiteralDfa3_0(active0, 0x400L, active1, 0x4L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L, active1, 0x8L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000L, active1, 0x40000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x5000800000208000L, active1, 0x400000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000040080L, active1, 0x804690120L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0xc8000810000L, active1, 0x4000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x932200008000000L, active1, 0x100000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x4004000000800L, active1, 0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x800000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000020000000L, active1, 0x1000042L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x12000000L, active1, 0x4600L);
      case 84:
      case 116:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(2, 14, 48);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(2, 26, 48);
         else if ((active0 & 0x100000000L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 58, 48);
         return jjMoveStringLiteralDfa3_0(active0, 0x30200101000L, active1, 0x8009010L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x200001000000000L, active1, 0L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x20000L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000000L, active1, 0L);
      case 89:
      case 121:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(2, 22, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x20000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x204000081400L, active1, 0x200082000L);
      case 66:
      case 98:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 50, 48);
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000L, active1, 0L);
      case 67:
      case 99:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(3, 25, 48);
         return jjMoveStringLiteralDfa4_0(active0, 0x1800000000000L, active1, 0x414L);
      case 68:
      case 100:
         if ((active1 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(3, 96, 48);
         break;
      case 69:
      case 101:
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x20000a8200000000L, active1, 0x840410aL);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x110000000000000L, active1, 0L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x40000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x88402490000080L, active1, 0x1000L);
      case 75:
      case 107:
         if ((active1 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(3, 93, 48);
         break;
      case 76:
      case 108:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 18, 48);
         else if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(3, 35, 48);
         else if ((active1 & 0x20L) != 0L)
         {
            jjmatchedKind = 69;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000040020000L, active1, 0x44800000L);
      case 77:
      case 109:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 57, 48);
         return jjMoveStringLiteralDfa4_0(active0, 0xa00000L, active1, 0x4000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000000000L, active1, 0x2000000000L);
      case 79:
      case 111:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 8, 48);
         else if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(3, 79, 48);
         return jjMoveStringLiteralDfa4_0(active0, 0x20100000L, active1, 0x800100000L);
      case 80:
      case 112:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(3, 11, 48);
         return jjMoveStringLiteralDfa4_0(active0, 0x10000L, active1, 0L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000000000L, active1, 0L);
      case 82:
      case 114:
         if ((active0 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 44;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x1003000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000008000L, active1, 0L);
      case 84:
      case 116:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 54, 48);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x400000241L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x210000L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa4_0(active0, 0x22000008000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000L, active1, 0x40000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000L, active1, 0x6000400L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0x12000000001000L, active1, 0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x800400000L);
      case 69:
      case 101:
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x200000L) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(4, 98, 48);
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L, active1, 0x41010000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L, active1, 0L);
      case 71:
      case 103:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 60, 48);
         return jjMoveStringLiteralDfa5_0(active0, 0x210000000L, active1, 0L);
      case 72:
      case 104:
         if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(4, 68, 48);
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000000L, active1, 0L);
      case 73:
      case 105:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 46, 48);
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000L, active1, 0x4000800043L);
      case 75:
      case 107:
         if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(4, 66, 48);
         break;
      case 76:
      case 108:
         if ((active1 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(4, 97, 48);
         return jjMoveStringLiteralDfa5_0(active0, 0x1040000000L, active1, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000080L, active1, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000L, active1, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000010000L, active1, 0x1000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x20000L);
      case 82:
      case 114:
         if ((active1 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 91, 48);
         return jjMoveStringLiteralDfa5_0(active0, 0x208000000000L, active1, 0x104208L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000000L, active1, 0x2000000000L);
      case 84:
      case 116:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 38, 48);
         else if ((active1 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 100, 48);
         return jjMoveStringLiteralDfa5_0(active0, 0x8920020000008400L, active1, 0x2100L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x4088000080080000L, active1, 0L);
      case 88:
      case 120:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 61, 48);
         break;
      case 89:
      case 121:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x80000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x1002000001000L, active1, 0x2000000041L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x2800000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000000L, active1, 0x400L);
      case 69:
      case 101:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(5, 10, 48);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 36, 48);
         else if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 62, 48);
         else if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(5, 72, 48);
         else if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(5, 77, 48);
         else if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(5, 84, 48);
         return jjMoveStringLiteralDfa6_0(active0, 0x8120000200000000L, active1, 0x80008L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x2L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x28060100080L, active1, 0x200L);
      case 75:
      case 107:
         if ((active1 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(5, 99, 48);
         break;
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x12000000080000L, active1, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x88000080000000L, active1, 0L);
      case 78:
      case 110:
         if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(5, 76, 48);
         return jjMoveStringLiteralDfa6_0(active0, 0x18800000L, active1, 0x1000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x40000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000210000L, active1, 0x20000L);
      case 83:
      case 115:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(5, 15, 48);
         else if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(5, 80, 48);
         else if ((active1 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(5, 94, 48);
         break;
      case 84:
      case 116:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(5, 34, 48);
         else if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 78, 48);
         else if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(5, 86, 48);
         else if ((active1 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 102, 48);
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000000L, active1, 0x4000000L);
      case 89:
      case 121:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 45, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x800080000010000L, active1, 0x800000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000000L, active1, 0L);
      case 67:
      case 99:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 39, 48);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x2000000200L);
      case 68:
      case 100:
         if ((active1 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(6, 83, 48);
         break;
      case 69:
      case 101:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 47, 48);
         else if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(6, 74, 48);
         else if ((active1 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(6, 90, 48);
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000L, active1, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000L, active1, 0x20000L);
      case 76:
      case 108:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 37, 48);
         else if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(6, 64, 48);
         else if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(6, 70, 48);
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000L, active1, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000L, active1, 0L);
      case 78:
      case 110:
         if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(6, 65, 48);
         return jjMoveStringLiteralDfa7_0(active0, 0x40100000L, active1, 0x8L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x12000000000000L, active1, 0L);
      case 82:
      case 114:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(6, 33, 48);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 48, 48);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x40000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000L, active1, 0L);
      case 84:
      case 116:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(6, 19, 48);
         else if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(6, 23, 48);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(6, 27, 48);
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000000080L, active1, 0x3000000L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa7_0(active0, 0x8120000000000000L, active1, 0L);
      case 89:
      case 121:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(6, 21, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1);
      return 7;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x1000000L);
      case 66:
      case 98:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 49, 48);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 52, 48);
         break;
      case 67:
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000L, active1, 0x8L);
      case 68:
      case 100:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(7, 28, 48);
         break;
      case 69:
      case 101:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(7, 12, 48);
         else if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 41, 48);
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000000080L, active1, 0x2000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x800000000000000L, active1, 0x40000L);
      case 76:
      case 108:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(7, 29, 48);
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000000000L, active1, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000000L, active1, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000L, active1, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x20000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000L, active1, 0L);
      case 84:
      case 116:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(7, 30, 48);
         else if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 53, 48);
         else if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 56, 48);
         else if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 63, 48);
         else if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(7, 73, 48);
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x2000800000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1);
      return 8;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(8, 87, 48);
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x8L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x2000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000000000000L, active1, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000000000L, active1, 0x40000L);
      case 80:
      case 112:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 43, 48);
         break;
      case 82:
      case 114:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(8, 7, 48);
         else if ((active1 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(8, 89, 48);
         return jjMoveStringLiteralDfa9_0(active0, 0x100000L, active1, 0x20000L);
      case 84:
      case 116:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(8, 31, 48);
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x1000000L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000000000000L, active1, 0L);
      case 89:
      case 121:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(8, 16, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1);
      return 9;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 51, 48);
         break;
      case 69:
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0x100000L, active1, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x1020000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x2000000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x40000L);
      case 83:
      case 115:
         if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(9, 67, 48);
         break;
      case 84:
      case 116:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 55, 48);
         else if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 59, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, active1);
      return 10;
   }
   switch(curChar)
   {
      case 73:
      case 105:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x40000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa11_0(active0, 0x100000L, active1, 0x1000000L);
      case 78:
      case 110:
         if ((active1 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 101, 48);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0, active1);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(9, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, active1);
      return 11;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa12_0(active0, 0x100000L, active1, 0x1000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa12_0(active0, 0L, active1, 0x40000L);
      case 89:
      case 121:
         if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(11, 81, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, active0, active1);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(10, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, active1);
      return 12;
   }
   switch(curChar)
   {
      case 78:
      case 110:
         return jjMoveStringLiteralDfa13_0(active0, 0x100000L, active1, 0L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa13_0(active0, 0L, active1, 0x1000000L);
      case 89:
      case 121:
         if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(12, 82, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(11, active0, active1);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(11, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, active1);
      return 13;
   }
   switch(curChar)
   {
      case 84:
      case 116:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(13, 20, 48);
         return jjMoveStringLiteralDfa14_0(active0, 0L, active1, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0, active1);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(12, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, 0L, active1);
      return 14;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa15_0(active1, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(13, 0L, active1);
}
private int jjMoveStringLiteralDfa15_0(long old1, long active1){
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(13, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, 0L, active1);
      return 15;
   }
   switch(curChar)
   {
      case 77:
      case 109:
         return jjMoveStringLiteralDfa16_0(active1, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(14, 0L, active1);
}
private int jjMoveStringLiteralDfa16_0(long old1, long active1){
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(14, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, 0L, active1);
      return 16;
   }
   switch(curChar)
   {
      case 80:
      case 112:
         if ((active1 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(16, 88, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(15, 0L, active1);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 48;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 108)
                        kind = 108;
                     { jjCheckNAddStates(0, 6); }
                  }
                  else if ((0x280000000000L & l) != 0L)
                     { jjCheckNAddStates(7, 9); }
                  else if (curChar == 46)
                     { jjCheckNAddTwoStates(18, 19); }
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 4;
                  else if (curChar == 35)
                  {
                     if (kind > 5)
                        kind = 5;
                     { jjCheckNAdd(1); }
                  }
                  if (curChar == 48)
                     { jjAddStates(10, 11); }
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 29:
                  if ((0x3ff001000000000L & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     { jjCheckNAdd(12); }
                  }
                  else if (curChar == 39)
                     { jjCheckNAdd(30); }
                  break;
               case 48:
               case 12:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  { jjCheckNAdd(12); }
                  break;
               case 0:
                  if (curChar != 45)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjCheckNAdd(1); }
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjCheckNAdd(1); }
                  break;
               case 3:
                  if (curChar != 35)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjCheckNAdd(1); }
                  break;
               case 4:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(5, 6); }
                  break;
               case 5:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(5, 6); }
                  break;
               case 6:
                  if (curChar == 42)
                     { jjCheckNAddStates(12, 14); }
                  break;
               case 7:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(8, 6); }
                  break;
               case 8:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(8, 6); }
                  break;
               case 9:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               case 10:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 15:
                  if ((0x3ff001000000000L & l) != 0L)
                     { jjAddStates(15, 16); }
                  break;
               case 17:
                  if (curChar == 46)
                     { jjCheckNAddTwoStates(18, 19); }
                  break;
               case 18:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(19); }
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 109)
                     kind = 109;
                  { jjCheckNAddTwoStates(19, 20); }
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 109)
                     kind = 109;
                  { jjCheckNAdd(21); }
                  break;
               case 22:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(23, 21); }
                  break;
               case 23:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(21); }
                  break;
               case 25:
                  if (curChar == 39)
                     { jjCheckNAdd(26); }
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(26, 27); }
                  break;
               case 27:
                  if (curChar == 39 && kind > 110)
                     kind = 110;
                  break;
               case 30:
                  if ((0x3000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(30, 31); }
                  break;
               case 31:
                  if (curChar == 39 && kind > 113)
                     kind = 113;
                  break;
               case 32:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAddStates(7, 9); }
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 108)
                     kind = 108;
                  { jjCheckNAdd(33); }
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(34, 17); }
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(17, 20); }
                  break;
               case 36:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(35); }
                  break;
               case 37:
                  if (curChar == 46)
                     { jjCheckNAdd(38); }
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 109)
                     kind = 109;
                  { jjCheckNAddTwoStates(40, 39); }
                  break;
               case 40:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(39); }
                  break;
               case 41:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(40, 39); }
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 108)
                     kind = 108;
                  { jjCheckNAddStates(0, 6); }
                  break;
               case 43:
                  if (curChar == 48)
                     { jjAddStates(10, 11); }
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 111)
                     kind = 111;
                  jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 47:
                  if ((0x3000000000000L & l) == 0L)
                     break;
                  if (kind > 114)
                     kind = 114;
                  jjstateSet[jjnewStateCnt++] = 47;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     { jjCheckNAddTwoStates(11, 12); }
                  }
                  else if (curChar == 96)
                     { jjCheckNAdd(14); }
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  else if ((0x100000001000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 29:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     { jjCheckNAdd(12); }
                  }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     { jjCheckNAddTwoStates(11, 12); }
                  }
                  break;
               case 48:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     { jjCheckNAdd(12); }
                  }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     { jjCheckNAddTwoStates(11, 12); }
                  }
                  break;
               case 1:
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 5:
                  { jjCheckNAddTwoStates(5, 6); }
                  break;
               case 7:
               case 8:
                  { jjCheckNAddTwoStates(8, 6); }
                  break;
               case 11:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  { jjCheckNAddTwoStates(11, 12); }
                  break;
               case 12:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  { jjCheckNAdd(12); }
                  break;
               case 13:
                  if (curChar == 96)
                     { jjCheckNAdd(14); }
                  break;
               case 14:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddStates(21, 23); }
                  break;
               case 15:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(15, 16); }
                  break;
               case 16:
                  if (curChar == 96 && kind > 104)
                     kind = 104;
                  break;
               case 20:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(24, 25); }
                  break;
               case 24:
                  if ((0x100000001000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 26:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjAddStates(26, 27); }
                  break;
               case 28:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 38:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(28, 29); }
                  break;
               case 44:
                  if ((0x100000001000000L & l) != 0L)
                     { jjCheckNAdd(45); }
                  break;
               case 45:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 111)
                     kind = 111;
                  { jjCheckNAdd(45); }
                  break;
               case 46:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 5:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddTwoStates(5, 6); }
                  break;
               case 7:
               case 8:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddTwoStates(8, 6); }
                  break;
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 48 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, "\47", "\42", "\73", "\50", "\51", "\75", "\54", "\77", };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   t.image = curTokenImage;

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   33, 34, 17, 36, 35, 37, 38, 33, 34, 35, 44, 46, 6, 7, 9, 15, 
   16, 36, 35, 37, 38, 14, 15, 16, 21, 22, 26, 27, 39, 41, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrException(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrException.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public SQLParserTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new RuntimeException("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public SQLParserTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 48; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrException("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrException.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xffffffffffffff01L, 0x7fef1ffffffffffL, 
};
static final long[] jjtoSkip = {
   0xfeL, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x0L, 0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[48];
    private final int[] jjstateSet = new int[2 * 48];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
